Controllers/CyberGTController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GTCorp.Controllers
{
    public class CyberGTController : Controller
    {
        // GET: CyberGT
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Galeria()
        {
            return View();
        }

        public ActionResult Contacto()
        {
            return View();
        }
    }
}

Controllers/GTDesignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GTCorp.Controllers
{
    public class GTDesignController : Controller
    {
        // GET: GTDesign
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Galeria()
        {
            return View();
        }
        public ActionResult Contacto()
        {
            return View();
        }
    }
}

Controllers/TacitaShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GTCorp.Controllers
{
    public class TacitaShopController : Controller
    {
        // GET: TacitaShop
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Contacto()
        {
            return View();
        }
    }
}

Controllers/TallerLotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GTCorp.Controllers
{
    public class TallerLotoController : Controller
    {
        // GET: TallerLoto
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Servicios()
        {
            return View();
        }

        public ActionResult Contacto()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/jquery.excoloSlider.css" />
    <link rel="stylesheet" href="~/Content/shadowbox.css" />

    <meta property="og:url" content="https://www.facebook.com/taller.loto/" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="GT-Corp" />
    <meta property="og:description" content="Servicios tecnológicos en Ziracuaretiro, Michoacán." />
    <meta property="og:image" content="http://www.your-domain.com/path/image.jpg" />

    <script src="~/Content/js/jquery.min.js"></script>
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="~/Content/js/jquery.excoloSlider.min.js"></script>
    <script src="~/Content/js/shadowbox.js"></script>
    <script type="text/javascript">Shadowbox.init();</script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                <a href='@Url.Action("Index","Home")' class="pull-left"><img src="~/Content/img/GT-Corp.png" width="100" /></a>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink(" Cyber-GT", "Index", "Home", new object { }, new { @class = "cyber glyphicon glyphicon-print"})</li>
                        <li>@Html.ActionLink(" GT-Design", "About", "Home", new object { }, new { @class = "gtdesign glyphicon glyphicon-gift" })</li>
                        <li>@Html.ActionLink(" Taller Loto", "Contact", "Home", new object { }, new { @class = "taller glyphicon glyphicon-flash" })</li>
                        <li>@Html.ActionLink(" Videofilmaciones", "Contact", "Home", new object { }, new { @class = "videofilm glyphicon glyphicon-facetime-video" })</li>
                        <li>@Html.ActionLink(" Tacita de Café", "Contact", "Home", new object { }, new { @class = "tacita glyphicon glyphicon-shopping-cart" })</li>*@
                    <li>
                        <a href='@Url.Action("Index","CyberGT")' class="cyber">
                            @*<span class="glyphicon glyphicon-print"></span>*@
                            <img src="~/Content/img/logo_cyber.png" width="35" />
                            Cyber-gt
                        </a>
                    </li>
                    <li>
                        <a href='@Url.Action("Index","GTDesign")' class="gtdesign">
                            @*<span class="glyphicon glyphicon-gift"></span>*@
                            <img src="~/Content/img/logo_design.png" width="35" />
                            GT Design
                        </a>
                    </li>
                    <li>
                        <a href='@Url.Action("Index","TallerLoto")' class="taller">
                            @*<span class="glyphicon glyphicon-flash"></span>*@
                            <img src="~/Content/img/mini_loto.png" width="35" />
                            Taller Loto
                        </a>
                    </li>
                    <li>
                        <a href='@Url.Action("Index","VideoGeminis")' class="videofilm">
                            @*<span class="glyphicon glyphicon-facetime-video"></span>*@
                            <img src="~/Content/img/mini_geminis.png" width="25" />
                            VideoFilmaciones Géminis
                        </a>
                    </li>
                    <li>
                        <a href='@Url.Action("Index","TacitaShop")' class="tacita">
                            @*<span class="glyphicon glyphicon-shopping-cart" ></span>*@
                            <img src="~/Content/img/mini_tacita.png" width="30" />
                            La tacita de café
                        </a>
                    </li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Realizado por Luis Eduardo González Téllez & Giovani Daniel De la Cruz Martínez</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>