Controllers/VideoGeminisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GTCorp.Controllers
{
    public class VideoGeminisController : Controller
    {
        // GET: VideoGeminis
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Contacto()
        {
            return View();
        }
    }
}

Views/VideoGeminis/Contacto.cshtml
@{
    ViewBag.Title = "Acerca de";
}


<div class="jumbotron text-center">
    <img src="~/Content/img/GT-Corp.png" width="600" />
</div>


<h3>@ViewBag.Message</h3>

<address>

    Matamoros 117. Centro<br />
    Ziracuaretiro, Michoacán<br />
    <abbr title="Teléfono">Tel:</abbr>
    (423) 59 30348<br /><br />
    Horario<br />
    <strong>Lunes a Viernes: </strong> [09:00 - 14:00] y [17:00 - 21:00]<br />
    <strong>Domingos: </strong> [10:00 - 14:00] y [17:00 - 20:00]

</address>

<address>
    <strong>Contacto General:</strong>   <a href="mailto:gt-ziracua@gmail.com">gt-ziracua@gmail.com</a><br />

</address>

<a href='@Url.Action("Index","Home")'>Volver</a>

Views/VideoGeminis/Index.cshtml
@{
    ViewBag.Title = "Videofilmaciones Géminis";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/Content/Carousel/001.jpg" alt="Cyber-GT">
        </div>

        <div class="item">
            <img src="~/Content/Carousel/002.jpg" alt="Cyber-GT">
        </div>

        <div class="item">
            <img src="~/Content/Carousel/003.jpg" alt="Cyber-GT">
        </div>

        <div class="item">
            <img src="~/Content/Carousel/004.jpg" alt="Cyber-GT">
        </div>
        <div class="item">
            <img src="~/Content/Carousel/005.jpg" alt="Cyber-GT">
        </div>
    </div>


    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="jumbotron text-center">

    <img src="~/Content/img/logo_geminis_nuevo.png" class="img-responsive center-block" alt="Videofilmaciones Géminis" width="300" />
</div>

<div class="row">
    <div class="col-md-2">
        <ul class="list-group">
            <li class="list-group-item">
                <span><img src="~/Content/icons/faceboook.png" width="10" /></span>
                <a href="https://www.fb.com/taller.loto" target="_blank" class="textFBGeminis"> &nbsp;Video Géminis</a>
            </li>
            <li class="list-group-item">
                <span><img src="~/Content/icons/github .png" width="20" /></span>
                <a href="https://github.com/isc-luiseduardo" target="_blank" class="textFBGeminis">&nbsp; Github</a>
            </li>

        </ul>
    </div>
    <div class="col-md-2">
        <ul class="list-group">
            <!--<li class="list-group-item">
                <span><a href='@Url.Action("Servicios","VideoGeminis")' class="btn btn-primary">Servicios y Precios</a> </span>
            </li>-->
            <li class="list-group-item">
                <span><a href='@Url.Action("Contacto","VideoGeminis")' class="btn btnContactGeminis">Contáctanos ahora</a></span>
            </li>
        </ul>
    </div>
</div>